"""Default case studies seeded into MongoDB (fully manageable from the admin panel)."""

_OG = {
    "seo": "https://static.prod-images.emergentagent.com/jobs/d359b275-eede-4689-80cd-2a730fff7d73/images/7e0a8980c5cd47621462695024146259d1ca15e6613a513e52a6a12e0b58d079.jpeg",
    "ai": "https://static.prod-images.emergentagent.com/jobs/d359b275-eede-4689-80cd-2a730fff7d73/images/d6c34695bba52392c502c5058f069c1deb11cef627787817c4e7022142c149ec.jpeg",
    "web": "https://static.prod-images.emergentagent.com/jobs/d359b275-eede-4689-80cd-2a730fff7d73/images/dc595710d95518f13b1fadbaa06962ecd2b0f657e5ab1c983125a13b74ae309d.jpeg",
    "whatsapp": "https://static.prod-images.emergentagent.com/jobs/d359b275-eede-4689-80cd-2a730fff7d73/images/387e476a2095ee1f03ec86b2629694b5c631533339ee3b073e6b060b37534dbb.jpeg",
    "app": "https://static.prod-images.emergentagent.com/jobs/d359b275-eede-4689-80cd-2a730fff7d73/images/7273b14a69e9a67ee61d28be6fa666bda33c68cfe036160e440d69883e8792bd.jpeg",
    "ads": "https://static.prod-images.emergentagent.com/jobs/d359b275-eede-4689-80cd-2a730fff7d73/images/37057d8f00ef503c3da01405c06de0fe70b3217d8761296c0b4e093978df0626.jpeg",
}

CASE_SEED = [
    {
        "slug": "3x-organic-traffic-d2c-skincare", "category": "SEO", "metric": "3\u00d7",
        "metricLabel": "organic traffic in 5 months", "tag": "SEO \u00b7 GEO", "industry": "D2C Skincare",
        "region": "India / US", "duration": "5 months", "year": "2025", "order": 1,
        "cover": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
        "og": _OG["seo"], "title": "Tripling organic traffic for a D2C skincare brand",
        "excerpt": "A direct-to-consumer skincare brand was stuck at an organic plateau. A technical rebuild plus intent-driven, schema-rich content tripled organic sessions in five months \u2014 and the brand now shows up inside AI answers for its core category.",
        "challenge": "Good products and decent ads, but organic traffic had been flat for a year. The site was slow, content was thin, and category pages cannibalised each other for the same keywords. The brand was invisible in Google's AI Overviews and to answer engines like Perplexity.",
        "approach": [
            {"h": "Fix the foundation", "t": "Rebuilt on a fast stack, cleared Core Web Vitals, and set a clean information architecture so crawlers and users could actually navigate."},
            {"h": "Consolidate & target intent", "t": "Merged competing pages, mapped 40+ commercial and informational keywords, and shipped answer-first content built around real buyer questions."},
            {"h": "Engineer for AI (GEO)", "t": "Added Organization, Product, FAQ and Article schema plus entity-rich copy so the brand became quotable inside AI answers, not just Google."},
            {"h": "Compound with content", "t": "A publishing cadence of comparison and how-to pieces, internally linked, that kept building topical authority month over month."},
        ],
        "results": [
            {"value": "3\u00d7", "label": "organic traffic"}, {"value": "+38%", "label": "revenue from organic"},
            {"value": "92", "label": "avg. Core Web Vitals score"}, {"value": "40+", "label": "ranking pages shipped"},
        ],
        "services": ["freelance-seo-expert", "freelance-website-developer"],
        "stack": ["Technical SEO", "GEO / Schema", "Content strategy", "React"],
        "chart": {"label": "Monthly organic sessions", "before": 8000, "after": 24000, "suffix": "", "higherIsBetter": True},
        "quote": {"text": "Rajeev rebuilt our site and our organic traffic tripled in five months. He treats your business like his own.", "name": "Priya Nair", "role": "Founder, D2C skincare brand"},
    },
    {
        "slug": "80-percent-faster-support-saas", "category": "AI", "metric": "80%",
        "metricLabel": "faster first response", "tag": "AI Automation", "industry": "B2B SaaS",
        "region": "UK / EU", "duration": "6 weeks", "year": "2025", "order": 2,
        "cover": "https://images.unsplash.com/photo-1684369175833-4b445ad6bfb5?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
        "og": _OG["ai"], "title": "Cutting first-response time 80% with an AI support & lead bot",
        "excerpt": "A growing SaaS team was drowning in repetitive questions and losing leads outside office hours. An AI assistant on WhatsApp and the website cut first-response time by 80% and now qualifies leads around the clock \u2014 with no extra headcount.",
        "challenge": "Support and sales were handled by the same small team. Response times slipped during peak hours, and leads who messaged after hours often went cold before anyone replied. Every new hire only pushed the problem down the road.",
        "approach": [
            {"h": "Map the real questions", "t": "Analysed months of chats and tickets to find the 20% of questions driving 80% of the volume."},
            {"h": "Build a grounded assistant", "t": "Deployed an AI assistant trained on the product docs and FAQs, wired into WhatsApp and the site, with clean human handoff."},
            {"h": "Qualify & route leads", "t": "Added a lead-qualification flow that captures intent, budget and timeline, then routes hot leads straight to the team 24/7."},
            {"h": "Measure & tune", "t": "Instrumented response time, deflection rate and lead capture, then tuned prompts weekly against real transcripts."},
        ],
        "results": [
            {"value": "80%", "label": "faster first response"}, {"value": "24/7", "label": "lead qualification"},
            {"value": "-64%", "label": "repetitive tickets"}, {"value": "0", "label": "extra headcount needed"},
        ],
        "services": ["freelance-ai-consultant", "whatsapp-marketing-freelancer"],
        "stack": ["AI agents", "WhatsApp API", "Python", "Automation"],
        "chart": {"label": "Avg. first-response time (min)", "before": 45, "after": 9, "suffix": " min", "higherIsBetter": False},
        "quote": {"text": "The WhatsApp automation alone paid for the whole engagement. Fast, senior, no fluff.", "name": "Daniel Roberts", "role": "Ops Lead, B2B SaaS"},
    },
    {
        "slug": "52-percent-conversion-retail-rebuild", "category": "Web", "metric": "+52%",
        "metricLabel": "conversion rate", "tag": "Web \u00b7 Software", "industry": "Multi-location Retail",
        "region": "UAE / GCC", "duration": "8 weeks", "year": "2026", "order": 3,
        "cover": "https://images.unsplash.com/photo-1758524944006-ba8116008496?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
        "og": _OG["web"], "title": "A custom rebuild that lifted retail conversion 52%",
        "excerpt": "A multi-location retailer was leaking sales to a slow, bloated theme and a clunky checkout. A custom, sub-second rebuild with a streamlined checkout lifted conversion 52% and cut bounce rate by a third.",
        "challenge": "The store ran on a heavy off-the-shelf theme. Pages took seconds to load on mobile, the checkout had too many steps, and analytics showed shoppers abandoning at payment. Ad spend was working, but the site was wasting the clicks.",
        "approach": [
            {"h": "Rebuild for speed", "t": "Replaced the theme with a custom, sub-second front end and optimised images, fonts and scripts for mobile-first performance."},
            {"h": "Streamline the checkout", "t": "Cut the checkout to the essential steps, added trusted payment options and clear progress cues."},
            {"h": "Remove friction", "t": "Fixed navigation, search and product pages so shoppers could find and buy in fewer taps."},
            {"h": "Prove it with data", "t": "A/B tested key changes and tracked conversion, bounce and average order value to lock in the wins."},
        ],
        "results": [
            {"value": "+52%", "label": "conversion rate"}, {"value": "-33%", "label": "bounce rate"},
            {"value": "<1s", "label": "median load time"}, {"value": "+21%", "label": "average order value"},
        ],
        "services": ["freelance-website-developer", "freelance-software-developer"],
        "stack": ["React", "Performance", "UX", "Custom checkout"],
        "chart": {"label": "Conversion rate (%)", "before": 1.9, "after": 2.9, "suffix": "%", "higherIsBetter": True},
        "quote": {"text": "We hired an agency first and wasted months. Rajeev fixed it in weeks \u2014 and explained every decision.", "name": "Ahmed Hassan", "role": "Director, Retail"},
    },
    {
        "slug": "42-percent-revenue-whatsapp-fnb", "category": "Marketing", "metric": "42%",
        "metricLabel": "of revenue from WhatsApp", "tag": "WhatsApp Marketing", "industry": "F&B chain (12 outlets)",
        "region": "India", "duration": "4 months", "year": "2025", "order": 4,
        "cover": "https://images.unsplash.com/photo-1633354931133-27ac1ee5d853?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
        "og": _OG["whatsapp"], "title": "Turning WhatsApp into 42% of revenue for an F&B chain",
        "excerpt": "A 12-outlet food & beverage chain had a big customer list but no way to bring people back. Opt-in WhatsApp campaigns, automated re-orders and smart broadcasts turned the channel into 42% of total revenue in four months.",
        "challenge": "Thousands of past customers sat in spreadsheets and POS exports, untouched. Repeat business relied on luck and location. Discount blasts on other channels were expensive and barely converted.",
        "approach": [
            {"h": "Build a clean opt-in list", "t": "Consolidated customer data and grew a compliant, opt-in WhatsApp audience with QR codes at outlets and online."},
            {"h": "Automate re-orders", "t": "Set up one-tap re-order flows and cart reminders so regulars could reorder favourites in seconds."},
            {"h": "Broadcast with intent", "t": "Segmented by outlet and behaviour, then sent timed offers and new-item drops instead of spray-and-pray blasts."},
            {"h": "Close the loop", "t": "Tracked revenue per broadcast and iterated on timing, copy and offers weekly."},
        ],
        "results": [
            {"value": "42%", "label": "of revenue from WhatsApp"}, {"value": "3.1\u00d7", "label": "repeat orders"},
            {"value": "68%", "label": "broadcast open rate"}, {"value": "12", "label": "outlets onboarded"},
        ],
        "services": ["whatsapp-marketing-freelancer", "freelance-digital-marketing-consultant"],
        "stack": ["WhatsApp API", "Automation", "Segmentation", "CRM"],
        "chart": {"label": "Share of revenue from WhatsApp (%)", "before": 6, "after": 42, "suffix": "%", "higherIsBetter": True},
        "quote": {"text": "Rajeev turned a dusty customer list into our single best sales channel. It runs almost on its own now.", "name": "Karan Mehta", "role": "Marketing Head, F&B chain"},
    },
    {
        "slug": "50k-downloads-fitness-app", "category": "App", "metric": "50k+",
        "metricLabel": "downloads in 90 days", "tag": "App \u00b7 Mobile", "industry": "Fitness startup",
        "region": "US / EU", "duration": "5 months", "year": "2025", "order": 5,
        "cover": "https://images.pexels.com/photos/4162581/pexels-photo-4162581.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=1400",
        "og": _OG["app"], "title": "Shipping a fitness app to 50k+ downloads in 90 days",
        "excerpt": "A fitness startup needed a fast, reliable cross-platform app \u2014 on a deadline. A cleanly engineered build launched on iOS and Android and crossed 50,000 downloads in its first 90 days with a 4.8\u2605 rating.",
        "challenge": "A previous agency had shipped a buggy, slow prototype that crashed on older phones. The team needed a stable, scalable app they could iterate on, plus a launch that actually landed.",
        "approach": [
            {"h": "Re-architect for stability", "t": "Rebuilt the app on a maintainable cross-platform stack with proper state management and offline handling."},
            {"h": "Polish the core loop", "t": "Focused engineering on the workout and progress screens users touch daily, with smooth, native-feeling motion."},
            {"h": "Ship to both stores", "t": "Handled iOS and Android release pipelines, review requirements and a staged rollout to catch issues early."},
            {"h": "Instrument & iterate", "t": "Wired analytics and crash reporting so the team could ship confident weekly updates post-launch."},
        ],
        "results": [
            {"value": "50k+", "label": "downloads in 90 days"}, {"value": "4.8\u2605", "label": "app store rating"},
            {"value": "-42%", "label": "crash rate vs old app"}, {"value": "3", "label": "platforms shipped"},
        ],
        "services": ["freelance-app-developer", "freelance-software-developer"],
        "stack": ["Cross-platform", "Native UX", "CI/CD", "Analytics"],
        "chart": {"label": "Downloads in first 90 days", "before": 4000, "after": 50000, "suffix": "", "higherIsBetter": True},
        "quote": {"text": "The app shipped on time, ran smoothly from day one, and our users genuinely love it.", "name": "Lena Fischer", "role": "Founder, Fitness startup"},
    },
    {
        "slug": "38-percent-lower-cac-google-ads", "category": "Marketing", "metric": "-38%",
        "metricLabel": "cost per acquisition", "tag": "Digital Marketing", "industry": "B2B services",
        "region": "UK / US", "duration": "Ongoing retainer", "year": "2026", "order": 6,
        "cover": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
        "og": _OG["ads"], "title": "Halving lead costs for a B2B services firm",
        "excerpt": "A B2B services firm was spending more each quarter for fewer leads. Rebuilding the funnel \u2014 tighter targeting, better landing pages and clean tracking \u2014 cut cost per acquisition 38% while more than doubling qualified leads.",
        "challenge": "Ad spend kept climbing but leads were flat and often unqualified. Campaigns were broad, landing pages were generic, and conversion tracking was unreliable, so no one knew what actually worked.",
        "approach": [
            {"h": "Fix the tracking", "t": "Rebuilt conversion tracking end-to-end so every lead could be attributed to the campaign and keyword that drove it."},
            {"h": "Tighten targeting", "t": "Cut wasted spend, restructured campaigns around high-intent terms and excluded the queries that never converted."},
            {"h": "Rebuild landing pages", "t": "Shipped focused, fast landing pages with clear offers and one obvious action per page."},
            {"h": "Optimise on data", "t": "Shifted budget to winners weekly and continuously tested copy, creative and offers."},
        ],
        "results": [
            {"value": "-38%", "label": "cost per acquisition"}, {"value": "+2.4\u00d7", "label": "qualified leads"},
            {"value": "+63%", "label": "landing page conversion"}, {"value": "4:1", "label": "blended ROAS"},
        ],
        "services": ["freelance-digital-marketing-consultant", "freelance-seo-expert"],
        "stack": ["Google Ads", "Conversion tracking", "Landing pages", "CRO"],
        "chart": {"label": "Cost per acquisition ($)", "before": 82, "after": 51, "suffix": "", "prefix": "$", "higherIsBetter": False},
        "quote": {"text": "Leads more than doubled while our cost per lead dropped. Finally, marketing that pays for itself.", "name": "Olivia Grant", "role": "CMO, B2B services"},
    },
]
